# Generated by Django 4.0.4 on 2023-03-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Communitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('course_details', models.CharField(choices=[('Difficulty levels', (('easy', 'Easy'), ('medium', 'Intermediate'), ('hard', 'Hard')))], max_length=50)),
                ('type_of_course', models.CharField(choices=[('Course Type ', (('instructor-led', 'Instructor-Led'), ('on-demand', 'On-Demand'), ('both', 'Both')))], max_length=50)),
                ('lessons_offered', models.CharField(choices=[('Lessons', (('1', 'Lesson one'), ('2', 'Lesson two'), ('3', 'Lesson three')))], max_length=50)),
                ('assessment', models.CharField(choices=[('Practical Assessment', (('assessment_one', 'Assessment-One'),))], max_length=50)),
                ('programming_languages', models.CharField(choices=[('Programming Languages', (('java', 'Java'), ('python', 'Python'), ('javascript', 'JavaScript')))], max_length=50)),
                ('frameworks', models.CharField(choices=[('Frameworks', (('java', 'Spring'), ('python', 'Django'), ('javascript', 'ReactJs')))], max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('specialty', models.CharField(max_length=100)),
                ('community', models.CharField(max_length=100)),
                ('programming_language', models.CharField(choices=[('Programming Languages', (('java', 'Java'), ('python', 'Python'), ('javascript', 'JavaScript')))], max_length=100)),
                ('framework', models.CharField(choices=[('Frameworks', (('java', 'Spring'), ('python', 'Django'), ('javascript', 'ReactJs')))], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('Frameworks', (('java', 'Spring'), ('python', 'Django'), ('javascript', 'ReactJs')))], max_length=100)),
                ('programming_language', models.CharField(choices=[('Programming Languages', (('java', 'Java'), ('python', 'Python'), ('javascript', 'JavaScript')))], max_length=100)),
                ('complexity', models.CharField(max_length=100)),
                ('modules', models.CharField(max_length=50)),
                ('tasks', models.CharField(max_length=100)),
                ('community', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.communitie')),
            ],
        ),
    ]
