# Generated by Django 4.0.4 on 2023-03-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_complexity_alter_project_modules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_details',
            field=models.CharField(default='welcome', max_length=100),
            preserve_default=False,
        ),
    ]
