# Generated by Django 4.0.4 on 2023-03-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_article_article_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_details',
            field=models.TextField(),
        ),
    ]
